### PR TITLE
Updated link to the git pages doc

### PR DESCRIPTION
**Pull request by cyntran**
Link was broken. I just updated it to the right subdomain.

### CODE REVIEW

**Comment by Bluefitdev** [comment]
This actually just helped me! Thanks

**Review by bilal-elchami — APPROVED** [review]

**Review by tido64 — APPROVED** [review]

**Comment by bilal-elchami** [comment]
Should update the URL in the repo description too

**Comment by tido64** [comment]
@cyntran: Thanks ❤️

**Comment by Krizzu** [comment]
There's a lot to be updated from RN Community to this org, so feel free to contribute 🙏

**Comment by tido64** [comment]
@bilal-elchami: Yup, thanks for the reminder.

**Pull request merged**
