### PR TITLE
chore: bump react-native to 0.68

### PR DESCRIPTION
**Pull request by tido64**
## Summary

Bumps react-native to 0.68.

## Test Plan

Make sure that `yarn start:*` works:

- [x] Android
- [x] iOS
- [x] macOS
- [x] Windows

### CODE REVIEW

**Comment by tido64** [comment]
@krizzu: Would you mind taking a look at Android? I got build errors I'm not sure how to proceed on. I'll take a look on Windows in the meantime.

**Comment by krizzu** [comment]
@tido64 so the problem is that test-app has bumped to Kotlin 1.7. So we have to solutions:

- Use KSP instead of KAPT for annotation processing. This requires few steps, [like described in this SO post](https://stackoverflow.com/a/72978960).
- Update Room to 2.5.0-alpha02, which has Kotlin 1.7 compatibility 

With first one, it's hard to assess how much of impact it would be on project that'd depend on AsyncStorage, which are still on lower version of Kotlin. It'd be good to test this KSP integration with lower Kt version to see if it's still compatible. 

Second one has drawback of Room requiring compilation/target sdk of 32. That means developer should migrate in project to those version and check compatibility of the rest of the app.

I'd be in favor on going with first approach, but would have to test the scenario first.

**Comment by tido64** [comment]
> @tido64 so the problem is that test-app has bumped to Kotlin 1.7

I've added a flag to the test app so we can set our own Kotlin version and opened #832 to track support of 1.7. Everything should be building again now.

**Review by krizzu — APPROVED** [review]
Yes, let's not block it 👌

**Pull request merged**
