### PR TITLE
fix: update old references to @react-native-community

### PR DESCRIPTION
**Pull request by tido64**
Summary:
---------

We still have references to `@react-native-community` that we need to update.

Test Plan:
----------

CI should pass.

### CODE REVIEW

**Review by Krizzu — APPROVED** [review]
Great 🙏

**Comment by Bardiamist** [comment]
@Krizzu Hello, can I know why async-storage migrated to this repository?

**Comment by tido64** [comment]
@Bardiamist: Please see [Why repository was moved out from react-native-community?](https://github.com/react-native-async-storage/async-storage/discussions/507)

**Pull request merged**
